--convert-thumbnails png

--embed-metadata

--embed-thumbnail

--embed-subs

--embed-info-json

--embed-chapters

# MKV is a ubiquitous format and also supports arbitrary metadata fields so we can stick
# whatever we get from the video platform in there.
--merge-output-format mkv

# Specify English subtitles and exclude live chat data from being downloaded.
--sub-langs "en.*,-live_chat"
